# name: deployment

# on:
#   push:
#     branches: ['main']

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 20
#           #   cache: npm
#           cache: pnpm

#       - uses: pnpm/action-setup@v2
#         with:
#           version: 9

#       - name: Install dependencies
#         run: pnpm install

#       - name: Build
#         run: pnpm build:pre

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.WF_TOKEN }}
#           publish_dir: ./docs
